
export const DataColumnsLiraReport = [
        'Id',
        'Município',
        'UF',
        'Bairro',
        'Data da Visita',
        'Supervisor',
        'Data Resultado Laboratório',
        'Responsável',
        'Nome',
        'Número Quarteirão',
        'Logradouro',
        'Complemento',
        'Tipo Imóvel',
        'Depósito A1',
        'Depósito A2',
        'Depósito B',
        'Depósito C',
        'Depósito D1',
        'Depósito D2',
        'Depósito E',
        'Amostras',
        'Túbitos',
        'Túbitos Examinados Laboratório',
        'Túbitos Aedes Aegypti',
        'Túbitos Aedes Albopictus',
        'Depósitos A1 Aedes Aegypti',
        'Depósitos A2 Aedes Aegypti',
        'Depósitos B Aedes Aegypti',
        'Depósitos C Aedes Aegypti',
        'Depósitos D1 Aedes Aegypti',
        'Depósitos D2 Aedes Aegypti',
        'Depósitos E Aedes Aegypti',
        'Depósitos Aedes Albopictus',
        'Latitude',
        'Longitude'
    ]

export const DataColumnsHoversLiraReport =  [
    'Identificador da visita atual',
    'Município em que a visita foi realizada',
    'Unidade da federação do município',
    'Bairro em que a visita foi realizada',
    'Data da visita de campo',
    'Supervisor da visita de campo',
    'Data dos resultados do laboratório',
    'Responsável pelos resultados do laboratório',
    'Nome do agente que realizou as visitas',
    'Número do quarteirão',
    'Logradouro do imóvel',
    'Complemento do imóvel',
    'Tipo do imóvel',
    'Caixa d’água elevada',
    'Caixa d’água a nível do solo, tonel, balde de água da chuva, fontes',
    'Prato/vaso de flor, pote de água de animais, piscina desmontável de plástico, coisas pequenas',
    'Ralo, piscina de chão, chafariz',
    'Pneu',
    'Sucata, lixo, entulho',
    'Bromélia, folha de coqueiro, folha de bananeira, ocos de troncos de árvore, depósitos naturais',
    'Número das amostras que foram coletadas',
    'Número de túbitos coletados pra armazenar as amostras',
    'Túbitos examinados pelo laboratório',
    'Túbitos com Aedes aegypti',
    'Túbitos com Aedes albopictus',
    'Depósitos tipo A1 com Aedes aegypti',
    'Depósitos tipo A2 com Aedes aegypti',
    'Depósitos tipo B com Aedes aegypti',
    'Depósitos tipo C com Aedes aegypti',
    'Depósitos tipo D1 com Aedes aegypti',
    'Depósitos tipo D2 com Aedes aegypti',
    'Depósitos tipo E com Aedes aegypti',
    'Depósitos com Aedes albopictus',
    'Latitude da visita',
    'Longitude da visita'
] 

export const DataExportCsvHeadersLiraReport = [
    { label: 'Id', key: 'id' },
    { label: 'Município', key: 'municipio' },
    { label: 'UF', key: 'uf' },
    { label: 'Bairro', key: 'bairro' },
    { label: 'Data da Visita', key: 'campoData' },
    { label: 'Supervisor', key: 'supervisor' },
    { label: 'Data Resultado Laboratório', key: 'labData' },
    { label: 'Responsável', key: 'responsavel' },
    { label: 'Nome', key: 'nome' },
    { label: 'Número Quarteirão', key: 'numQuart' },
    { label: 'Logradouro', key: 'logradouro' },
    { label: 'Complemento', key: 'complemento' },
    { label: 'Tipo Imóvel', key: 'tipoImv' },
    { label: 'Depósito A1', key: 'depA1' },
    { label: 'Depósito A2', key: 'depA2' },
    { label: 'Depósito B', key: 'depB' },
    { label: 'Depósito C', key: 'depC' },
    { label: 'Depósito D1', key: 'depD1' },
    { label: 'Depósito D2', key: 'depD2' },
    { label: 'Depósito E', key: 'depE' },
    { label: 'Amostras', key: 'amostras' },
    { label: 'Túbitos', key: 'tubitos' },
    { label: 'Túbitos Examinados Laboratório', key: 'labEx' },
    { label: 'Túbitos Aedes Aegypti', key: 'labAeg' },
    { label: 'Túbitos Aedes Albopictus', key: 'labAlb' },
    { label: 'Depósitos A1 Aedes Aegypti', key: 'aegDepA1' },
    { label: 'Depósitos A2 Aedes Aegypti', key: 'aegDepA2' },
    { label: 'Depósitos B Aedes Aegypti', key: 'aegDepB' },
    { label: 'Depósitos C Aedes Aegypti', key: 'aegDepC' },
    { label: 'Depósitos D1 Aedes Aegypti', key: 'aegDepD1' },
    { label: 'Depósitos D2 Aedes Aegypti', key: 'aegDepD2' },
    { label: 'Depósitos E Aedes Aegypti', key: 'aegDepE' },
    { label: 'Depósitos Aedes Albopictus', key: 'depAlb' },
    { label: 'Latitude', key: 'latitude' },
    { label: 'Longitude', key: 'longitude'}
]