

export const DataColumnsVisit = [
    'Id',
    'Código Município',
    'Nome do Bairro',
    'Zona',
    'Tipo',
    'Data',
    'Ciclo',
    'Agente',
    'Atividade',
    'Numero do Quarteirão',
    'Lado do Quarteirão',
    'Nome do Logradouro',
    'Número do Imóvel',
    'Sequência Imóvel',
    'Tipo de Imóvel',
    'Tipo de Visita',
    'Pendência',
    'Depósito A1',
    'Depósito A2',
    'Depósito B',
    'Depósito C',
    'Depósito D1',
    'Depósito D2',
    'Depósito E',
    'Imóvel Inspecionado',
    'Número Amostra Inicial',
    'Número Amostra Final',
    'Quantidade de Túbitos',
    'Depósito Eliminado',
    'Imóvel Tratado',
    '1º Tipo Larvicida',
    'Quantidade Utilizada 1º Larvicida',
    'Quantidade Depósito 1º Larvicida',
    '2º Tipo Larvicida',
    'Quantidade Depósito 2º Larvicida',
    'Quantidade Depósito 2º Larvicida',
    'Tipo Larvicida Perifocal',
    'Quantidade Larvicida Perifocal',
    'Latitude',
    'Longitude',
]


export const DataColumnsHoverVisit = [
    'Identificador da visita atual',
    'Código do município',
    'Nome do bairro',
    'Região do imóvel',
    'Tipo da localização',
    'Data da visita',
    'Ciclo do ano em que a visita foi feita',
    'Nome do agente',
    'Atividade que foi realizada',
    'Número do quarteirão',
    'Lado do quarteirão',
    'Logradouro do imóvel',
    'Número do imóvel',
    'Sequência de algum imóvel (Mais comum em casos de terrenos baldios que não têm um número)',
    'Tipo do imóvel',
    'Tipo da visita',
    'Pendência da visita ao imóvel',
    'Caixa d’Água elevada',
    'Caixa d’Água a nível do solo, tonel, balde de água da chuva, fontes',
    'Prato/Vaso de flor, pote de água de animais, piscina desmontável de plástico, coisas Pequenas',
    'Ralo, piscina de chão, chafariz',
    'Pneu',
    'Sucata, lixo, entulho',
    'Bromélia, folha de coqueiro, folha de bananeira, ocos de troncos de árvore, depósitos naturais',
    'Imóvel inspecionado caso foi possível completar a visita',
    'Número da amostra inicial coletada caso tenham sido encontrados mosquitos',
    'Número da amostra final coletada caso tenham sido encontrados mosquitos',
    'Quantidade de túbitos com amostras que foram coletados',
    'Depósito com mosquito que foi eliminado durante a visita de tratmento',
    'Imóvel foi tratado durante visita de tratamento',
    'Tipo do primeiro larvicida que foi utilizado durante visita de tratamento',
    'Quantidade utilizada em gramas do primeiro larvicida',
    'Quantidade de depósitos tratados com o primeiro larvicida',
    'Tipo do segundo larvicida que foi utilizado durante a visita de tratamento',
    'Quantidade utilizada em gramas do segundo larvicida',
    'Quantidade de depósitos tratados com o segundo larvicida',
    'Tipo do larvicida utilizado pra tratamento perifocal',
    'Quantidade de depósitos tratados com o tratamento perifocal',
    'Latitude da visita',
    'Longitude da visita',
]


export const DataExportCsvHeadersVisit = [
    { label: 'Id', key: "id" },
    { label: 'Código Município', key: "codMunicipio" },
    { label: 'Nome do Bairro', key: "nomeBairro" },
    { label: 'Zona', key: "zona" },
    { label: 'Tipo', key: "tipo" },
    { label: 'Data', key: "data" },
    { label: 'Ciclo', key: "ciclo" },
    { label: 'Agente', key: "agente" },
    { label: 'Atividade', key: "atividade" },
    { label: 'Numero do Quarteirão', key: "numQuart" },
    { label: 'Lado do Quarteirão', key: "ladoQuart" },
    { label: 'Nome do Logradouro', key: "nomeLogr" },
    { label: 'Número do Imóvel', key: "numImv" },
    { label: 'Sequência Imóvel', key: "seqImv" },
    { label: 'Tipo de Imóvel', key: "tipoImv" },
    { label: 'Tipo de Visita', key: "tipoVisita" },
    { label: 'Pendência', key: "pendencia" },
    { label: 'Depósito A1', key: "depA1" },
    { label: 'Depósito A2', key: "depA2" },
    { label: 'Depósito B', key: "depB" },
    { label: 'Depósito C', key: "depC" },
    { label: 'Depósito D1', key: "depD1" },
    { label: 'Depósito D2', key: "depD2" },
    { label: 'Depósito E', key: "depE" },
    { label: 'Imóvel Inspecionado', key: "imvInsp" },
    { label: 'Número Amostra Inicial', key: "numAmInic" },
    { label: 'Número Amostra Final', key: "numAmFim" },
    { label: 'Quantidade de Túbitos', key: "qtdTubitos" },
    { label: 'Depósito Eliminado', key: "depElim" },
    { label: 'Imóvel Tratado', key: "imvTrat" },
    { label: '1º Tipo Larvicida', key: "focLarv1Tipo" },
    { label: 'Quantidade Utilizada 1º Larvicida', key: "focLarv1G" },
    { label: 'Quantidade Depósito 1º Larvicida', key: "focLarv1Qtd" },
    { label: '2º Tipo Larvicida', key: "focLarv2Tipo" },
    { label: 'Quantidade Depósito 2º Larvicida', key: "focLarv2G" },
    { label: 'Quantidade Depósito 2º Larvicida', key: "focLarv2Qtd" },
    { label: 'Tipo Larvicida Perifocal', key: "perifocTipo" },
    { label: 'Quantidade Larvicida Perifocal', key: "perifocQtd" },
    { label: 'Latitude', key: "latitude" },
    { label: 'Longitude', key: "longitude" }
]